config/routes.rb
Rails.application.routes.draw do
  resources :resorts do
     resources :questions, only: [:create, :show]

    get 'favorites', to: 'favorites#create', as: 'create_favorite'
    get 'favorites/delete', to: 'favorites#destroy', as: 'delete_favorite'

  end


  resources :questions, only: [] do
    resources :answers, only: [:create]
  end


  # resources :questions do
  #   member do
  #     post "answers", to: "answers#create"
  #   end
  # end

  # post "resorts/:id/questions", to: "questions#create"
  # post "resorts/:id/questions/:id/answers", to: "answers#create"

  #   member do
  #     post "questions", to: "resorts#create_question"
  #     member do
  #       post "answers", to: "resorts#create_answer"
  #     end
  #   end

  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:show]

  root to: 'pages#home', as: 'home'

  get 'resorts/:id/ticket', to: 'pages#ticket', as: 'ticket'
  get 'resorts/:id/share', to: 'pages#share', as: 'share'
  get 'resorts/:id/itinerary', to: 'pages#itinerary', as: 'itinerary'



end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <div id="logo">Way to Snow</div>
    <% end %>

  <div class="links-holder">
    <%= link_to "Resort Map", resorts_path, style:"text-decoration:none", class: "link" %>
    <% if user_signed_in? %>
    <%= link_to "User Profile", user_path(current_user), style:"text-decoration:none", class: "link" %>
        <%#= link_to "Log out", destroy_user_session_path, method: :delete, style:"text-decoration:none", class: "link" %>
    <% else %>
        <%= link_to "Login", new_user_session_path, style:"text-decoration:none", class: "link" %>
    <% end %>
  </div>

</div>