config/routes.rb
Rails.application.routes.draw do
  resources :resorts do
     resources :questions, only: [:create, :show]

    get 'favorites', to: 'favorites#create', as: 'create_favorite'
    get 'favorites/delete', to: 'favorites#destroy', as: 'delete_favorite'

  end


  resources :questions, only: [] do
    resources :answers, only: [:create]
  end


  # resources :questions do
  #   member do
  #     post "answers", to: "answers#create"
  #   end
  # end

  # post "resorts/:id/questions", to: "questions#create"
  # post "resorts/:id/questions/:id/answers", to: "answers#create"

  #   member do
  #     post "questions", to: "resorts#create_question"
  #     member do
  #       post "answers", to: "resorts#create_answer"
  #     end
  #   end

  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:show]

  root to: 'pages#home', as: 'home'

  get 'resorts/:id/ticket', to: 'pages#ticket', as: 'ticket'
  get 'resorts/:id/share', to: 'pages#share', as: 'share'
  get 'resorts/:id/itinerary', to: 'pages#itinerary', as: 'itinerary'



end

app/views/pages/_itinerary_calc.html.erb
<div style="display: flex; justify-content: center">
  <div class="col-8">
    <div class="driving-cost">
      <form>
        <div class="row">
          <div class="col">
            <input type="text" class="form-control" id="travelers" data-action="change->itinerary#changeInput" placeholder="Number of travellers">
          </div>
          <div class="col">
            <input type="text" class="form-control" id="days" data-action="change->itinerary#changeInput" placeholder="Number of days">
          </div>
        </div>
      </form>
    </div>
  </div>
</div>


<div class="costs-table">
  <table class = "table">
    <colgroup>
      <col style="width:80px">
      <col style="width:100px">
      <col style="width:10px">
      <col style="width:130px">
      <col style="width:10px">
      <col style="width:80px">
    </colgroup>
    <tbody>
      <tr class ="category">
        <td>Lift ticket</td>
        <td>¥<span id="resort-price"><%= @resort.adult_price %></span></td>
        <td>*</td>
        <td><span id="travelers-display"></span></td>
        <td>=</td>
        <td>¥<span id="travelers-display-total"></span></td>
      </tr>
      <tr>
        <td>Fuel and tolls</td>
        <td>(avg. ¥31 per km)</td>
        <td>*</td>
        <td><span id="km-display"></span></td>
        <td>=</td>
        <td>¥<span id="km-cost"></span></td>
      </tr>
<!--         <tr>
        <td>Toll roads</td>
        <td>¥24.6 per km</td>
        <td>/</td>
        <td><span id="km-display2"></span></td>
        <td>=</td>
        <td>¥<span id="km-toll-cost"></span></td>
      </tr> -->
      <tr>
        <td></td>
        <td></td>
        <td></td>
        <td><strong>Grand Total</strong></td>
        <td>=</td>
        <td>¥<span id="grand-total-cost"></span></td>
      </tr>
      <tr>
        <td></td>
        <td></td>
        <td></td>
        <td>(approx. per person)</td>
        <td>=</td>
        <td>¥<span id="per-person-cost"></span></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/pages/home.html.erb
<div id="img-container">

  <div id="login-out-holder">
    <% if user_signed_in? %>
      <%#= link_to "Log out", destroy_user_session_path, method: :delete, style:"text-decoration:none", class: "login-out" %>
    <% else %>
      <%= link_to "Login", new_user_session_path, style:"text-decoration:none", class: "login-out" %>
    <% end %>
  </div>

  <div id="welcome-box">
    <div id="logo-home">Way to Snow</div>
    <div id="call-to-action-box">
      <%= link_to "Go", resorts_path, style:"text-decoration:none", id: "submit" %>
      <div id="tagline">find the perfect powder...</div>
    </div>
  </div>

</div>

app/views/pages/itinerary.html.erb
<div class="container col-8" data-controller="itinerary">

  <div class="resort-info-header mt-4 mb-3">DETAILED DIRECTIONS</div>
    <div style="display: flex; justify-content: center">
      <div class='map-button mb-3' style="width:300px"; data-markers="<%= @resort.to_json %>" data-action="click->itinerary#googleLink">Prefer the train?</div>
    </div>
    <div style="display: flex; justify-content: center">
      <div id="itinerary-map-holder" style="width: 90%">
        <div id="itinerary-map" data-controller="itinerary" data-action="google-maps-callback@window->itinerary#initMap" data-markers="<%= @resort.to_json %>"></div>
        <div id="right-panel"></div>
      </div>
    </div>

  <div class="resort-info-header mt-4">CALCULATE TRIP COST</div>
    <%= render 'pages/itinerary_calc', resort: @resort %>

  <div class="resort-info-header">SEND ITINERARY</div>
    <div style="display: flex; justify-content: center">
      <div class="col-8">
        <div class="send-form">
          <form>
            <div class="form-group">
              <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
            </div>
              <div class="send-itinerary"><%= link_to "SEND", resort_path, class:"itinerary-button" %></div>
          </form>
        </div>
      </div>
    </div>

</div>

<script>

  window.dispatchMapsEvent = function(...args) {
    const event = document.createEvent("Events")
    event.initEvent("google-maps-callback", true, true)
    event.args = args
    window.dispatchEvent(event)
  }

</script>

<script async defer
    src='https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_API_SERVER_KEY'] %>&callback=dispatchMapsEvent'>
    </script>

app/views/pages/share.html.erb
<div class="container col-8 mt-5">
  <h1 class="mb-5">Create itinerary for visit to <%= @resort.name.titlecase %>!</h1>
  <form>
    <div class="form-group row">
      <label for="text" class="col-4 col-form-label">Email</label>
      <div class="col-8">
        <div class="input-group">
          <div class="input-group-prepend">
            <div class="input-group-text">
              <i class="fa fa-address-card"></i>
            </div>
          </div>
          <input id="text" name="text" type="text" class="form-control">
        </div>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-4">Travel date:</label>
      <div class="col-8">
        <input type="date" id="start" name="trip-start"
         value="2020-03-01"
         min="2020-03-01" max="2020-03-29">
      </div>
    </div>

    <div class="form-group row">
      <label class="col-4">How many travelers:</label>
      <div class="col-8">
        <select name="travelers">
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
            <option value="6">6</option>
          </select>
      </div>
    </div>

    <div class="form-group row">
      <label for="textarea" class="col-4 col-form-label">Describe your plans</label>
      <div class="col-8">
        <textarea id="textarea" name="textarea" cols="40" rows="5" class="form-control"></textarea>
      </div>
    </div>
    <div class="form-group row">
      <div class="offset-4 col-8">
        <%= link_to "Send", home_path, style:"text-decoration:none", class: "btn btn-primary" %>
      </div>
    </div>
  </form>
</div>




<!--     <div class="custom-control custom-switch">
      <input type="checkbox" class="custom-control-input" id="customSwitch1">
      <label class="custom-control-label" for="customSwitch1">Snowboarding</label>
    </div>
    <div class="custom-control custom-switch">
      <input type="checkbox" class="custom-control-input" id="customSwitch2">
      <label class="custom-control-label" for="customSwitch1">Skiing</label>
    </div> -->

app/views/pages/ticket.html.erb
<div class="container">
  <div class="ticket">
    <h1 class="resort-title">Buy tickets for <%= @resort.name.upcase %></h1>
    <br>
    <p>Valid for 1 day pass</p>
    <p>¥<%= @resort.adult_price %></p>
    <div class="qr-code"><%= image_tag "ticket.png" %></div>
    <p>Present QR code at resort for day pass</p>
  </div>
</div>