config/routes.rb
Rails.application.routes.draw do
  resources :resorts do
     resources :questions, only: [:create, :show]

    get 'favorites', to: 'favorites#create', as: 'create_favorite'
    get 'favorites/delete', to: 'favorites#destroy', as: 'delete_favorite'

  end


  resources :questions, only: [] do
    resources :answers, only: [:create]
  end


  # resources :questions do
  #   member do
  #     post "answers", to: "answers#create"
  #   end
  # end

  # post "resorts/:id/questions", to: "questions#create"
  # post "resorts/:id/questions/:id/answers", to: "answers#create"

  #   member do
  #     post "questions", to: "resorts#create_question"
  #     member do
  #       post "answers", to: "resorts#create_answer"
  #     end
  #   end

  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:show]

  root to: 'pages#home', as: 'home'

  get 'resorts/:id/ticket', to: 'pages#ticket', as: 'ticket'
  get 'resorts/:id/share', to: 'pages#share', as: 'share'
  get 'resorts/:id/itinerary', to: 'pages#itinerary', as: 'itinerary'



end

app/models/resort.rb
class Resort < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  has_many :questions, dependent: :destroy
  has_many :forecasts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :weather_reports, dependent: :destroy
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode

  def conditions
    forecasts.map(&:condition)
  end
end

app/controllers/resorts_controller.rb
class ResortsController < ApplicationController
  before_action :validate_user

  def validate_user
    @user = current_user
  end

  def index
    if params[:best].present?
      @resorts = Resort.joins(:weather_reports, :forecasts)
        .where(weather_reports: { current: true })
        .where(forecasts: { condition: ['good', 'great'] })
        .where('forecasts.forecast_day::date = ?', Date.today) # + 1.day
    elsif params[:favorites].present?
      @user.favorites.any? ? @resorts = @user.resorts : @resorts = Resort.all
    else
      @resorts = Resort.all
    end
    @resorts = @resorts.includes(:weather_reports, :forecasts, :favorites).where("current = ?", true).references(:weather_reports)
    @markers = map_maker(@resorts)
    respond_to do |format|
      format.html
      format.json { render json:@markers }
    end
  end

  def map_maker(resorts)
    resorts.map do |resort|
      snow_depth = resort.weather_reports[0].snow_depth
      {
        lat: resort.latitude,
        lng: resort.longitude,
        conditions: resort.conditions,
        infoWindow: render_to_string(partial: "info_window", locals: { resort: resort, snow_depth: snow_depth }, formats: [:html])
      }
    end
  end

  def show
    @resort = Resort.friendly.find(params[:id])
    @question = Question.new
    @answer = Answer.new
  end
end

# REMOVED CODE FOR FILTERING WITH JSON...
# '?date=0&condition=good'
# @resorts = Resort.joins(:weather_reports, :forecasts)
# if(params[:date])
#   date = Date.today + params[:day].to_i.days
#   @resorts = @resorts.where('forecasts.forecast_day::date = ?', date )
# end
# if(condition = params[:condition])

#   @resorts = @resorts.where(forecasts: { condition: condition })
#     if (%w(good great).include?(condition))
#       @resorts = @resorts.where('weather_reports.snow_depth > ?', 50)
#     end
# end

app/views/resorts/_directions.html.erb
<!-- <div class="container col-9" data-controller="itinerary">
<p id="travel-time">Travel time: <span></span></p>
  <div id="itinerary-map-holder"> -->
    <div id="itinerary-map" data-controller="itinerary" data-action="google-maps-callback@window->itinerary#initMap" data-markers="<%= @resort.to_json %>"></div>
<!--     <div id="right-panel"></div>
  </div> -->
<!--   <div id="map-buttons-holder">
    <div class='map-button' data-markers="<%= @resort.to_json %>" data-action="click->itinerary#googleLink">Prefer the train?</div>
  </div>


</div> -->

<script>

  window.dispatchMapsEvent = function(...args) {
    const event = document.createEvent("Events")
    event.initEvent("google-maps-callback", true, true)
    event.args = args
    window.dispatchEvent(event)
  }

</script>

<script async defer
    src='https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_API_SERVER_KEY'] %>&callback=dispatchMapsEvent'>
    </script>

app/views/resorts/_elevation.html.erb
<!-- <ul id="mountain">
  <li class="top">
    <div class="value"><%= @resort.top_elevation%> M</div>
    <div class="label">Top</div>
  </li>
  <li class="drop">
    <div class="value"><%= @resort.top_elevation - @resort.bottom_elevation %> M</div>
    <div class="label">Drop</div>
  </li>
  <li class="bottom">
    <div class="value"><%= @resort.bottom_elevation %> M</div>
    <div class="label">Bottom</div>
  </li>
</ul> -->

<div class="resort-info-items">
  <div class="resort-summary-card">
    <h1 style="color:#4A4A4A">TOP</h1>
    <h2><%= @resort.top_elevation %>m</h2>
  </div>

  <div class="resort-summary-card">
    <h1 style="color:#4A4A4A">BOTTOM</h1>
    <h2><%= @resort.bottom_elevation %>m</h2>
  </div>

  <div class="resort-summary-card">
    <h1 style="color:#4A4A4A">DROP</h1>
    <h2><%= @resort.top_elevation - @resort.bottom_elevation %>m</h2>
  </div>
</div>

app/views/resorts/_facilities.html.erb
<div class="resort-summary-card">
  <h1 style="color:#4A4A4A"><i class="fas fa-skiing fa-2x"></i></h1>
  <h1 style="color:#4A4A4A">Ski School</h1>
  <h2><%= @resort.ski_school ? '<i class="fas fa-check"></i>'.html_safe : '<i class="fas fa-times red"></i>'.html_safe %></h2>
</div>

<div class="resort-summary-card">
  <h1 style="color:#4A4A4A"><i class="fas fa-snowboarding fa-2x"></i></h1>
  <h1 style="color:#4A4A4A">Snowboard School</h1>
  <h2><%= @resort.sb_school ? '<i class="fas fa-check"></i>'.html_safe : '<i class="fas fa-times red"></i>'.html_safe %></h2>
</div>

<div class="resort-summary-card">
  <h1 style="color:#4A4A4A"><i class="fas fa-child fa-2x"></i></h1>
  <h1 style="color:#4A4A4A">Child Care</h1>
  <h2><%= @resort.child_care ? '<i class="fas fa-check"></i>'.html_safe : '<i class="fas fa-times red"></i>'.html_safe %></h2>
</div>

app/views/resorts/_forecast_overview.html.erb
<% day_after = (Time.now + 2.day).strftime("%A")%>
<% two_days_after = (Time.now + 3.day).strftime("%A")%>
<% days = ["Today", "Tomorrow", day_after, two_days_after ] %>

<% def change_condition_name(condition) %>
  <% if condition == "bad" %>
    <% "BAD" %>
  <% elsif condition == "average" %>
    <%= "DECENT" %>
  <% elsif condition == "good" %>
    <%= "FRESH SNOW" %>
  <% else %>
    <%= "POWDER DAY" %>
  <% end %>
<% end %>

<% resort.forecasts.each.with_index do |forecast, index| %>
  <div class="summary-card" id="<%= forecast.condition %>">
    <h1> <%= days[index].upcase %> </h1>
    <h2> <%= change_condition_name(forecast.condition) %> </h2>
  <div id="<%= forecast.condition %>-body">
    <div class="forecast-condition-header">
      <p><i class="fas fa-snowflake"></i> <b> <%= forecast.snow_amount.ceil %></b><small> cm</small></p>
      <p><i class="fas fa-cloud-rain"></i> <%= forecast.rain.ceil %><small> cm</small></p>
    </div>
    <div class="forecast-condition-footer mt-3 mb-1" style="border-top: 1px solid white; padding-top: 10px; display: flex; flex-direction: column; font-size: 10px">
      <div style="display: flex; justify-content: center; justify-content: space-evenly">
        <div style="width: 100px"><%= forecast.max_temperature %>&#176; max <i class="fas fa-temperature-high"></i></div>
        <div style="width: 100px"><i class="fas fa-wind"></i> <%= forecast.wind_speed %> km/h</div>
      </div>
      <div style="display: flex; justify-content: center; justify-content: space-evenly">
        <div style="width: 100px"><%= forecast.min_temperature %>&#176; min <i class="fas fa-temperature-low"></i></div>
        <div style="width: 100px"><i class="far fa-compass"></i></i> <%= forecast.wind_direction %></div>
      </div>
    </div>
  </div>
  </div>
<% end %>

app/views/resorts/_forecast_table.html.erb
<!-- replaced resort with resort -->

<table class="forecast-table">
  <thead>
    <tr>
      <th scope="col" class="table-header" width="150px;"></th>
      <th scope="col" class="table-header" width="70px;"><%= Time.now.strftime("%A") %></th>
      <th scope="col" class="table-header" width="70px;"><%= (Time.now + 1.day).strftime("%A") %></th>
      <th scope="col" class="table-header" width="70px;"><%= (Time.now + 2.day).strftime("%A") %></th>
      <th scope="col" class="table-header" width="70px;"><%= (Time.now + 3.day).strftime("%A") %></th>
    </tr>
  </thead>
  <tbody>
    <% row_titles = ['Max Temperature', 'Min Temperature', 'Snowfall', 'Rain', 'Wind Direction', 'Wind Speed'] %>
    <% params = [:max_temperature, :min_temperature, :snow_amount, :rain, :wind_direction, :wind_speed] %>
    <% row_titles.each_with_index do |row_title, index| %>
      <%= '<tr>'.html_safe %>
        <%= "<th scope='row'>'#{row_title}'</th>".html_safe %>
          <!--         need to fix forecasts -->
          <% resort.forecasts[0..3].each do |forecast| %>
            <%= '<td>'.html_safe %>
              <%= forecast.method(params[index]).call %>
            <%= '</td>'.html_safe %>
          <% end %>
      <%= '</tr>'.html_safe %>
    <% end %>
  </tbody>
</table>

app/views/resorts/_info_window.html.erb
<% def change_condition_name(condition) %>
  <% if condition == "bad" %>
    <% "BAD" %>
  <% elsif condition == "average" %>
    <%= "DECENT" %>
  <% elsif condition == "good" %>
    <%= "FRESH SNOW" %>
  <% else %>
    <%= "POWDER DAY" %>
  <% end %>
<% end %>

  <div class="popup-header">
    <h1><%= resort.name.titlecase %></h1>
    <div data-controller="popup" >
    <% favorited = false %>
    <% if current_user %>
      <% current_user.favorites.each do |favorite|
      favorited = (resort.favorites.include?(favorite))||favorited
      end %>
    <% end %>

      <div style="font-size: 20px; margin-left: 16px; margin-bottom: 8px;"><i data-controller="popup" data-target="popup.heart" class="fas fa-heart button-favorite <%= favorited ? 'red' : '' %>" id="heart" style="text-decoration:none" data-action="click->popup#favorite" data-value="<%= resort.id %>" data-favorited="<%= favorited %>"></i></div>
    </div>
  </div>

    <div style="padding: 4px 0px; display: flex; justify-content: center; align-items: center; font-size: 12px; color: #4A4A4A">
      <div style="margin-right: 10px"><%= resort.town %>,&nbsp<%= resort.prefecture %></div>
      <div>&nbsp|&nbsp</div>
      <div style="margin-left: 10px;"><strong><%= snow_depth %></strong>&nbspcm of snow</div>
<!--       Travel time: <span data-target="popup.output" data-value="<%= resort.longitude %>, <%= resort.latitude %>"></span> -->
    </div>

    <% day_after = (Time.now + 2.day).strftime("%A")%>
    <% two_days_after = (Time.now + 3.day).strftime("%A")%>
    <% days = ["Today", "Tomorrow", day_after, two_days_after ] %>


<%= link_to resort_path(resort) do %>
    <div class="summary-items-popup">
      <% resort.forecasts.each.with_index do |forecast, index| %>
        <div class="popup-summary-card" id="<%= forecast.condition %>">
          <h4> <%= days[index].upcase %> </h4>
          <div id="<%= forecast.condition %>-body">
          <div class="forecast-condition-footer">
            <div style="font-size: 11px"> <%= change_condition_name(forecast.condition) %> </div>
          </div>
        </div>
        </div>
      <% end %>
    </div>
<% end %>

  </div>

app/views/resorts/_q&a.html.erb
  <div style="font-family: 'Open Sans'; font-size: 12px; color: #4A4A4A; margin: 10px 0px;">
    There <%= (@resort.questions.count.zero? || @resort.questions.count > 1) ? "are #{@resort.questions.count} questions" : "is #{@resort.questions.count} question" %> for <strong><%= @resort.name %>:</strong>
  </div>
  <%#= render 'questions/question_form', resort: @resort, question: @question %>
  <div id="questions">
    <%= render 'questions/question', resort: @resort, question: @question, answer: @answer %>
  </div>

app/views/resorts/_resort_overview.html.erb
<div class="resort-summary-card">
  <h1 style="color:#4A4A4A">LIFTS</h1>
  <h2><%= @resort.lifts %></h2>
</div>

<div class="resort-summary-card">
  <h1 style="color:#4A4A4A">COURSES</h1>
  <h2><%= @resort.courses %></h2>
</div>

<div class="resort-summary-card">
  <h1 style="color:#4A4A4A">LONGEST</h1>
  <h2><%= @resort.longest_course %>m</h2>
</div>

app/views/resorts/_terrain.html.erb
<% width = 400 %>

<div style="display: flex; flex-direction: column; margin-top: 10px; margin-bottom: 26px">
  <div class="terrain-holder">
    <div class="terrain-box" style="width: <%= (width * (@resort.beginner.to_f / 100)).round %>px; font-weight: 500;"><%= @resort.beginner if @resort.beginner > 0 %><%= '%' if @resort.beginner > 0 %></div>
    <div class="terrain-box" style="width: <%= (width * (@resort.intermediate.to_f / 100)).round %>px; font-weight: 500;"><%= @resort.intermediate if @resort.intermediate > 0 %><%= '%' if @resort.intermediate > 0 %></div>
    <div class="terrain-box" style="width: <%= (width * (@resort.advanced.to_f / 100)).round %>px; font-weight: 500;"><%= @resort.advanced if @resort.advanced > 0 %><%= '%' if @resort.advanced > 0 %></div>
  </div>
  <div class="terrain-holder">
    <div class="terrain-box" id="beginner" style="width: <%= (width * (@resort.beginner.to_f / 100)).round %>px"></div>
    <div class="terrain-box" id="intermediate" style="width: <%= (width * (@resort.intermediate.to_f / 100)).round %>px"></div>
    <div class="terrain-box" id="advanced" style="width: <%= (width * (@resort.advanced.to_f / 100)).round %>px"></div>
  </div>
  <div class="terrain-holder">
    <div class="terrain-box" style="width: <%= (width * (@resort.beginner.to_f / 100)).round %>px"><%= 'BEGINNER' if @resort.beginner > 0 %></div>
    <div class="terrain-box" style="width: <%= (width * (@resort.intermediate.to_f / 100)).round %>px"><%= 'INTERMEDIATE' if @resort.intermediate > 0 %></div>
    <div class="terrain-box" style="width: <%= (width * (@resort.advanced.to_f / 100)).round %>px"><%= 'ADVANCED' if @resort.advanced > 0 %></div>
  </div>
</div>

app/views/resorts/_ticket_prices.html.erb
<div class="resort-info-items">
  <div class="resort-summary-card">
    <h1 style="color:#4A4A4A">ADULT</h1>
    <h2>¥&nbsp<%= @resort.adult_price %></h2>
  </div>

  <div class="resort-summary-card">
    <h1 style="color:#4A4A4A">CHILD</h1>
    <h2>¥&nbsp<%= @resort.child_price %></h2>
  </div>
</div>

app/views/resorts/index.html.erb
<div id="map-container" data-controller="maps">
  <div class="resort-counter">
    <span data-target="maps.counter" id="resort-counter-number"></span>
    <div style="font-family: 'Karla'; font-size: 14px; margin-top: 8px; color: #04507C;">RESORTS SHOWN</div>
  </div>

  <div class="sidebar">
    <div style="display: flex; flex-direction: column; align-items: flex-start; margin: 10px 0px;">
      <div style="display: flex; align-items: center; justify-content: flex-start; margin: 10px 0px 5px 0px;">
        <div class="condition-key-marker great" style="pointer-events:none"></div>
        <div style="font-family: 'Karla'; font-size: 14px; color: #04507C; margin-left: 10px;">POWDER DAY</div>
      </div>
      <div style="margin-left: 30px;">More than 10cm of snow</div>
    </div>
    <div style="display: flex; flex-direction: column; align-items: flex-start; margin: 10px 0px;">
      <div style="display: flex; align-items: center; justify-content: flex-start; margin: 10px 0px 5px 0px;">
        <div class="condition-key-marker good" style="pointer-events:none"></div>
        <div style="font-family: 'Karla'; font-size: 14px; color: #04507C; margin-left: 10px;">FRESH SNOW</div>
      </div>
      <div style="margin-left: 30px;">Up to 10 cm of snow</div>
    </div>
    <div style="display: flex; flex-direction: column; align-items: flex-start; margin: 10px 0px;">
      <div style="display: flex; align-items: center; justify-content: flex-start; margin: 10px 0px 5px 0px;">
        <div class="condition-key-marker average" style="pointer-events:none"></div>
        <div style="font-family: 'Karla'; font-size: 14px; color: #04507C; margin-left: 10px;">DECENT</div>
      </div>
      <div style="margin-left: 30px;">No new snow</div>
    </div>
    <div style="display: flex; flex-direction: column; align-items: flex-start; margin: 10px 0px;">
      <div style="display: flex; align-items: center; justify-content: flex-start; margin: 10px 0px 5px 0px;">
        <div class="condition-key-marker bad" style="pointer-events:none"></div>
        <div style="font-family: 'Karla'; font-size: 14px; color: #04507C; margin-left: 10px;">BAD</div>
      </div>
      <div style="margin-left: 30px;">Raining, windy or no snow</div>
    </div>
  </div>

  <div class="sidebar-mobile">
    <div style="display: flex; flex-direction: column; align-items: flex-start; margin: 10px 0px;">
      <div style="display: flex; align-items: center; justify-content: flex-start; margin: 0px 0px 0px 0px;">
        <div class="condition-key-marker great" style="pointer-events:none"></div>
        <div style="font-family: 'Karla'; font-size: 14px; color: #04507C; margin-left: 10px;">POWDER DAY</div>
      </div>
    </div>
    <div style="display: flex; flex-direction: column; align-items: flex-start; margin: 10px 0px;">
      <div style="display: flex; align-items: center; justify-content: flex-start; margin: 0px 0px 0px 0px;">
        <div class="condition-key-marker good" style="pointer-events:none"></div>
        <div style="font-family: 'Karla'; font-size: 14px; color: #04507C; margin-left: 10px;">FRESH SNOW</div>
      </div>
    </div>
    <div style="display: flex; flex-direction: column; align-items: flex-start; margin: 10px 0px;">
      <div style="display: flex; align-items: center; justify-content: flex-start; margin: 0px 0px 0px 0px;">
        <div class="condition-key-marker average" style="pointer-events:none"></div>
        <div style="font-family: 'Karla'; font-size: 14px; color: #04507C; margin-left: 10px;">DECENT</div>
      </div>
    </div>
    <div style="display: flex; flex-direction: column; align-items: flex-start; margin: 10px 0px;">
      <div style="display: flex; align-items: center; justify-content: flex-start; margin: 0px 0px 0px 0px;">
        <div class="condition-key-marker bad" style="pointer-events:none"></div>
        <div style="font-family: 'Karla'; font-size: 14px; color: #04507C; margin-left: 10px;">BAD</div>
      </div>
    </div>
  </div>

  <div id="map-buttons-holder">
    <div class="map-button selected" data-action="click->maps#filter click->maps#select" data-value="">All resorts</i></div>
    <div class="map-button" data-action="click->maps#filter click->maps#select" data-value="best=true"><%= '<i class="far fa-snowflake"></i>&nbsp&nbspToday`s Best'.html_safe %> </div>
<!--     <div class="map-button" data-action="click->maps#filter click->maps#select" data-value="new_snow=true"><i class="far fa-snowflake"></i>&nbsp&nbspFresh powder</div>
    <div class="map-button" data-action="click->maps#filter click->maps#select" data-value="lots_snow=true"><i class="far fa-snowflake"></i>&nbsp&nbspDeep snow</div> -->
    <div class="map-button" data-action="click->maps#filter click->maps#select" data-value="favorites=true"><%= '<i class="fas fa-heart"></i>&nbsp&nbspFavorites'.html_safe %> </div>
    <div class="map-button" data-action="click->maps#exposeSlider click->maps#filter" id="time-machine-button"><%= '<i class="fas fa-filter"></i>&nbsp&nbspFilters'.html_safe %> </div>
  </div>


  <div id="map-slider-holder">
    <div id="map-slider-holder-inside">

      <div class="range">
        <input data-target="maps.slider" data-action="change->maps#changeDay" type="range" min="0" max="3" steps="1" value="0" id='slider'>
        <div class="day-labels">
          <div class="day active">TODAY</div>
          <div class="day"><%= (Time.now + 1.day).strftime("%A").upcase %></div>
          <div class="day"><%= (Time.now + 2.day).strftime("%A").upcase %></div>
          <div class="day"><%= (Time.now + 3.day).strftime("%A").upcase %></div>
        </div>
      </div>

      <div class="form-check form-check-inline" id="form-check-row">
        <div>
          <input class="form-check-input" data-action="change->maps#newFilter" type="checkbox" value="average" id="averageCheck">
          <label class="form-check-label" for="averageCheck">DECENT</label>
        </div>
        <div>
          <input class="form-check-input" data-action="change->maps#newFilter" type="checkbox" value="good" id="goodCheck">
          <label class="form-check-label" for="goodCheck">FRESH SNOW</label>
        </div>
        <div>
          <input class="form-check-input" data-action="change->maps#newFilter" type="checkbox" value="great" id="greatCheck">
          <label class="form-check-label" for="greatCheck">POWDER DAY</label>
        </div>
      </div>

    </div>
  </div>

  <div id="map" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
<!--
<form>
  <div class="form-group">
    <div class="form-group">
      <label for="formControlRange">Example Range input</label>
      <input type="range" min="0" max="3" steps="1" value="0" class="form-control-range" id="formControlRange">
    </div>
    <div class="form-check form-check-inline">
      <input class="form-check-input" type="checkbox" value="great" id="defaultCheck1">
      <label class="form-check-label" for="defaultCheck1">
        Great
      </label>
      <input class="form-check-input" type="checkbox" value="good" id="defaultCheck2">
      <label class="form-check-label" for="defaultCheck1">
        Good
      </label>
      <input class="form-check-input" type="checkbox" value="average" id="defaultCheck3">
      <label class="form-check-label" for="defaultCheck1">
        Average
      </label>
      <input class="form-check-input" type="checkbox" value="bad" id="defaultCheck4">
      <label class="form-check-label" for="defaultCheck1">
        Bad
      </label>
    </div>
  </div>
  <button type="submit" class="btn btn-primary" data-action="click->maps#newFilter">Submit</button>
</form> -->

</div>

app/views/resorts/show.html.erb
<% content_for :meta_title, "#{@resort.name} is on #{DEFAULT_META["meta_product_name"]}" %>

<div class="container col-9">

  <div class="resort-show-banner">

    <div class="space-holder"></div>

    <div class="resort-names">
      <div class="resort-name"><%= @resort.name.titlecase %></div>
      <div class="resort-name-ja"><%= @resort.name_ja %></div>
      <div class="create-itinerary"><%= link_to "GO THERE", itinerary_path, class:"itinerary-button" %></div>
    </div>

    <div class="icon-holder">
      <% if current_user %>
        <% favorited = current_user.resorts.include?(@resort) %>
        <div><i data-controller="popup" data-target="popup.heart" class="fas fa-heart button-favorite <%= favorited ? 'red' : '' %>" id="heart" style="text-decoration:none" data-action="click->popup#favorite" data-value="<%= @resort.id %>" data-favorited="<%= favorited %>"></i></div>
      <% end %>
    </div>

  </div>

    <div style="padding: 4px 0px; display: flex; justify-content: center; align-items: center; font-size: 10px; color: #4A4A4A">
      <%= @resort.town %>,&nbsp<%= @resort.prefecture %>&nbsp|&nbsp
      <%= @resort.phone_number %>&nbsp|&nbsp
      <%= link_to "Official site&nbsp<i class='fas fa-external-link-alt'></i>".html_safe, "#{@resort.url}", target: :_blank, style: "text-decoration:none"  %>
    </div>

<!-- Displaying the weather overview cards, good, bad etc. -->
<div class="summary-items">
  <%= render 'resorts/forecast_overview', resort: @resort %>
</div>

<!-- This is the first bootstrap row contains everything below the banner image -->

  <div class="row">

<!-- This is the left side of the show page -->

    <div class="col" id="show-left-side">
      <div class="resort-info-block">
        <div class="resort-info-header">OVERVIEW</div>
        <div style="font-size: 12px; color: #4A4A4A; margin: 20px 20px 0px 20px; ">
          <%= @resort.name %> resort in <%= @resort.town %>, <%= @resort.prefecture %> prefecture has a planned season from <%= @resort.season_planned.gsub('Planned season: ','') %>.
        </div>
        <div class="resort-info-body">
          <div class="resort-info-items">
            <%= render 'resorts/resort_overview', resort: @resort %>
          </div>
        </div>
      </div>

      <div class="resort-info-block">
        <div class="resort-info-header">ELEVATION</div>
        <div class="resort-info-body">
          <%= render 'resorts/elevation', resort: @resort %>
        </div>
      </div>

      <div class="resort-info-block">
        <div class="resort-info-header">TICKET PRICES</div>
        <div style="font-size: 12px; color: #4A4A4A; margin: 20px 20px 0px 20px; ">
          There are special discounts available. Please check the <%= link_to "resort website", "#{@resort.url}", style: "text-decoration:none" %> for specific price information.
        </div>
        <div class="resort-info-body">
          <%= render 'resorts/ticket_prices', resort: @resort %>
        </div>
      </div>

      <div class="resort-info-block">
        <div class="resort-info-header">FACILITIES</div>
          <div class="resort-info-body">
            <div class="resort-info-items">
            <%= render 'resorts/facilities', resort: @resort %>
            </div>
          </div>
      </div>

<!-- This is the end of the left column -->

    </div>

<!-- This is the right side of the show page -->

    <div class="col" id="show-right-side">

      <div class="resort-info-block">
        <div class="resort-info-header">TERRAIN DIFFICULTY</div>
        <div class="resort-info-body">
          <%= render 'resorts/terrain', resort: @resort %>
        </div>
      </div>

      <div class="resort-info-block">
        <div class="resort-info-header">GETTING THERE</div>
          <div class="resort-info-body" style="padding: 20px">
          <%= render 'resorts/directions', resort: @resort %>
          </div>
        </div>
      </div>


<!--       <div class="resort-info-block">
        <div class="resort-info-header">WEATHER DATA</div>
        <div class="resort-info-body">
          <%#= render 'resorts/forecast_table', resort: @resort %>
        </div>
      </div> -->

<!-- This is the end of the right column -->
    </div>

<!-- This is the end of the first bootstrap row -->
  </div>

<!-- This is the Q&A on its own bootstrap row and in one column -->

  <div class="row">

    <div class="container col-6">

      <div class="resort-info-block">
        <div class="resort-info-header">Q&A</div>
        <div class="resort-info-body">
          <div id="questions_answers">
            <% if @resort.questions.blank? %>
              <div style="font-family: 'Open Sans'; font-size: 12px; color: #4A4A4A; margin-bottom: 10px;">
                Be the first to ask a question for <%= @resort.name %>!
              </div>

              <%= render 'questions/question_form', resort: @resort, question: @question %>
            <% else %>
              <%= render 'resorts/q&a', resort: @resort, question: @question, answer: @answer %>
              <%= render 'questions/question_form', resort: @resort, question: @question %>
            <% end %>
          </div>
        </div>
      </div>

    </div>
  </div>

<!-- This is the end of the Q&A -->

<!-- End of container -->

</div>